language: go
go:
  - 1.6.2
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
  - VERSION=1.0.1-beta
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}_R${TRAVIS_COMMIT}"
  - ghr --username loogo --token $GITHUB_TOKEN --replace --prerelease --debug v${VERSION} dist/