language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username doracl --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/